server:
  port: 80
  shutdown: graceful

spring:
  application:
    name: demo
  sql:
    init:
      schema-locations: classpath:demo-schema.sql
      data-locations: classpath:demo-data.sql
      mode: always
  datasource:
    url: jdbc:h2:./h2/demo
    driver-class-name: org.h2.Driver
    username: sa
    password: 123456
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    open-in-view: false
  security:
    user:
      name: admin
      password: 123456
