use demo;

CREATE TABLE IF NOT EXISTS "user" (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(64) NOT NULL,
	PASSWORD VARCHAR(64),
	PHONE VARCHAR(11),
	CREATE_DATE TIMESTAMP
);
COMMENT ON COLUMN "user".ID IS '用户ID';
COMMENT ON COLUMN "user".NAME IS '用户名称';
COMMENT ON COLUMN "user".PASSWORD IS '用户密码';
COMMENT ON COLUMN "user".PHONE IS '用户手机号码';
COMMENT ON COLUMN "user".CREATE_DATE IS '用户创建时间';
