version: '3.9'
configs:
  mysql-my.cnf: 
    external: true
services:
  mysql:
    image: mysql:8.0.31
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    configs:
      - source: mysql-my.cnf
        target: /etc/mysql/my.cnf
    volumes:
      - /opt/deploy/databases/mysql/var/lib/mysql:/var/lib/mysql
  postgres:
    image: postgres:15.0-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 123456
    volumes:
      - /opt/deploy/databases/postgres/data:/var/lib/postgresql
    